### ISSUE TITLE
No NIB support

### ISSUE THREAD

**Issue by wilkinnh** [shaps80/Abracadabra#2]
Based on SPXSecureVault.m:273, it looks like the passcode view controller is instantiated by calling the static 'new' method (shorthand for alloc init). Can this be updated to instantiate the view controller from a NIB or Storyboard?

**Comment by shaps80** [comment]
I just started using a better tool for tracking all my issues on GitHub and have only just been made aware of this one. Apologies for never getting back to you. Hope you solved the problem anyway?

**Comment by shaps80** [comment]
The demo app shows an implementation of this being loaded specifically from a Storyboard/Nib -- so this has always been supported. 

Thanks.
